### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.viewNews_jsp

### ISSUE THREAD

**Issue by jonathanmtran** [Jasig/NewsReaderPortlet#75]
**Describe the bug**
With NewsReaderPortlet-5.0.1, the portlet throws a java.lang.ClassNotFoundException exception.

I believe this is a side-effect of 2c1ceac as the newer version of taglibs-standard-impl has a dependency on Xalan (See CHANGES.txt in https://archive.apache.org/dist/tomcat/taglibs/taglibs-standard-1.2.1/taglibs-standard-1.2.1-source-release.zip)

**To Reproduce**
1. Update to NewsReaderPortlet-5.0.1
2. Try to use the portlet

**Expected behavior**
A functioning News Reader portlet

**Stacktrace**
```
ERROR [uP-PortletExec-13-guest-RENDER-[cpp-news-polycentric]] o.s.web.portlet.DispatcherPortlet 2018-08-29 12:59:31,012 - Could not complete request
javax.portlet.PortletException: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.viewNews_jsp
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.doDispatch(PortletRequestDispatcherImpl.java:185)
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:222)
	at org.springframework.web.portlet.DispatcherPortlet.doDispatch(DispatcherPortlet.java:1198)
	at org.springframework.web.portlet.DispatcherPortlet.doRender(DispatcherPortlet.java:1175)
	at org.springframework.web.portlet.DispatcherPortlet.render(DispatcherPortlet.java:1130)
	at org.springframework.web.portlet.DispatcherPortlet.doRenderService(DispatcherPortlet.java:789)
	at org.springframework.web.portlet.FrameworkPortlet.processRequest(FrameworkPortlet.java:536)
	at org.springframework.web.portlet.FrameworkPortlet.doDispatch(FrameworkPortlet.java:483)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:251)
	at org.apereo.portal.portlet.container.FilterChainImpl.doFilter(FilterChainImpl.java:179)
	at org.apereo.portal.portlet.container.FilterChainImpl.processFilter(FilterChainImpl.java:95)
	at org.apereo.portal.portlet.container.FilterManagerImpl.processFilter(FilterManagerImpl.java:114)
	at org.apache.pluto.container.driver.PortletServlet.dispatch(PortletServlet.java:340)
	at org.apache.pluto.container.driver.PortletServlet.doGet(PortletServlet.java:261)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.invoke(DefaultPortletInvokerService.java:233)
	at org.apache.pluto.driver.container.DefaultPortletInvokerService.render(DefaultPortletInvokerService.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:84)
	at org.apereo.portal.portlet.dao.jpa.ThreadContextClassLoaderAspect.doThreadContextClassLoaderUpdate(ThreadContextClassLoaderAspect.java:63)
	at sun.reflect.GeneratedMethodAccessor231.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:627)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:616)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy519.render(Unknown Source)
	at org.apache.pluto.container.impl.PortletContainerImpl.doRender(PortletContainerImpl.java:157)
	at org.apereo.portal.portlet.rendering.PortletRendererImpl.doRender(PortletRendererImpl.java:456)
	at org.apereo.portal.portlet.rendering.PortletRendererImpl.doRenderMarkup(PortletRendererImpl.java:275)
	at org.apereo.portal.portlet.rendering.worker.PortletRenderExecutionWorker.callInternal(PortletRenderExecutionWorker.java:69)
	at org.apereo.portal.portlet.rendering.worker.PortletRenderExecutionWorker.callInternal(PortletRenderExecutionWorker.java:33)
	at org.apereo.portal.portlet.rendering.worker.PortletExecutionWorker$1.call(PortletExecutionWorker.java:185)
	at org.apereo.portal.portlet.rendering.worker.PortletExecutionWorker$ExecutionLifecycleCallable.call(PortletExecutionWorker.java:225)
	at org.apereo.portal.portlet.rendering.worker.PortletExecutionCallable.call(PortletExecutionCallable.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.jsp.WEB_002dINF.jsp.viewNews_jsp
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:129)
	at org.apache.jasper.servlet.JasperLoader.loadClass(JasperLoader.java:60)
	at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:159)
	at org.apache.jasper.servlet.JspServletWrapper.getServlet(JspServletWrapper.java:171)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:380)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:386)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:330)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:268)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:160)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.ViewRendererServlet.renderView(ViewRendererServlet.java:114)
	at org.springframework.web.servlet.ViewRendererServlet.processRequest(ViewRendererServlet.java:86)
	at org.springframework.web.servlet.ViewRendererServlet.doGet(ViewRendererServlet.java:66)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:591)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:527)
	at org.apache.pluto.container.impl.PortletRequestDispatcherImpl.doDispatch(PortletRequestDispatcherImpl.java:174)
	... 54 common frames omitted
```

**Comment by jonathanmtran** [comment]
I initially ran into this on our non-production server, but I managed to reproduce the issue locally

**Comment by jonathanmtran** [comment]
I deleted `tomcat/work` and redeployed v5.0.1. The issue still persists

**Comment by bjagg** [comment]
Hi Jonathan,

In webapps/NewsReaderPortlet/WEB-INF/lib/ do you see different versions of taglibs, xalan, xerces, etc.?

Try `./gradlew :overlays:NewsReaderPortlet:clean :overlays:NewsReaderPortlet:tomcatDeploy` to clear it up.

**Comment by bjagg** [comment]
Mind trying to upgrade it and see if it works in your environment?

I have have NewsReader 2.6.0 working locally.

**Comment by jonathanmtran** [comment]
Here's what I've been trying

* Downgraded to 5.0.0: Works as expected
* Upgraded to 5.0.1: Doesn't work
* Apply #76 to 5.0.1: Works as expected

For good measure, I blew away `$HOME/.m2` and `$HOME/.gradle/caches`, and `./gradlew tomcatInstall tomcatDeploy`

¯\_(ツ)_/¯

**Comment by drewwills** [comment]
Here's what I've been trying
    - Downgraded to 5.0.0: Works as expected
    - Upgraded to 5.0.1: Doesn't work
    - Apply #76 to 5.0.1: Works as expected
    For good measure, I blew away $HOME/.m2 and $HOME/.gradle/caches, and ./gradlew tomcatInstall tomcatDeploy

It seems like you've done all the right things, and your analysis/solution is probably appropriate.

**Comment by bjagg** [comment]
Awesome! I'll test, merge and release soon.
